export enum UserRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  EDITOR = "EDITOR",
  VIEWER = "VIEWER",
  EXTERNAL_REVIEWER = "EXTERNAL_REVIEWER",
}

export enum SocialPlatform {
  FACEBOOK_PAGE = "FACEBOOK_PAGE",
  INSTAGRAM_BUSINESS = "INSTAGRAM_BUSINESS",
  THREADS = "THREADS",
  TWITTER = "TWITTER",
  LINKEDIN_PAGE = "LINKEDIN_PAGE",
  LINKEDIN_PROFILE = "LINKEDIN_PROFILE",
  TIKTOK = "TIKTOK",
  PINTEREST = "PINTEREST",
  YOUTUBE = "YOUTUBE",
  SNAPCHAT = "SNAPCHAT",
  REDDIT = "REDDIT",
  GOOGLE_BUSINESS = "GOOGLE_BUSINESS",
  CUSTOM_WEBHOOK = "CUSTOM_WEBHOOK",
}

export enum ContentStatus {
  DRAFT = "DRAFT",
  IN_REVIEW = "IN_REVIEW",
  APPROVED = "APPROVED",
  SCHEDULED = "SCHEDULED",
  PUBLISHED = "PUBLISHED",
  FAILED = "FAILED",
  ARCHIVED = "ARCHIVED",
}

export enum ScheduledPostStatus {
  QUEUED = "QUEUED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
  READY = "READY",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum PublishingJobStatus {
  QUEUED = "QUEUED",
  RUNNING = "RUNNING",
  SUCCEEDED = "SUCCEEDED",
  FAILED = "FAILED",
  RETRYING = "RETRYING",
  CANCELLED = "CANCELLED",
}

export enum AssetType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  CAROUSEL = "CAROUSEL",
  DOCUMENT = "DOCUMENT",
  AUDIO = "AUDIO",
}

export enum AutomationTrigger {
  POST_APPROVED = "POST_APPROVED",
  POST_PUBLISHED = "POST_PUBLISHED",
  POST_FAILED = "POST_FAILED",
  NEW_DRAFT = "NEW_DRAFT",
  NEW_COMMENT = "NEW_COMMENT",
  MANUAL = "MANUAL",
}

export enum AutomationAction {
  SCHEDULE_POST = "SCHEDULE_POST",
  UPDATE_DRAFT = "UPDATE_DRAFT",
  NOTIFY_SLACK = "NOTIFY_SLACK",
  SEND_EMAIL = "SEND_EMAIL",
  TRIGGER_N8N = "TRIGGER_N8N",
  CALL_WEBHOOK = "CALL_WEBHOOK",
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
}
